import { TutorialStep } from '../types';

export const TUTORIAL_STEPS: TutorialStep[] = [
  {
    id: 1,
    title: '1. Exploring the Loss Surface',
    subtitle: 'Understanding Loss Landscapes $J(w_1, w_2)$',
    objective: 'Rotate and zoom the 3D surface to locate the global minimum.',
    concept:
      'In Machine Learning, a Loss Surface represents how model error varies as weights w₁ and w₂ change. The goal of gradient descent is to walk downhill to find the lowest point (minimum loss).',
    formula: 'J(w_1, w_2) = \\frac{1}{2} w_1^2 + \\frac{3}{2} w_2^2',
    presetParams: {
      surfaceType: 'paraboloid',
      learningRate: 0.05,
      learningRateMode: 'optimal',
      momentum: 0,
      w1Initial: 3.5,
      w2Initial: 3.5,
      noise: 0,
    },
    verification: (_params, _steps, currentStep) => currentStep >= 0,
    hint: 'Use your mouse to click and rotate the 3D view. Notice how the paraboloid curves downward toward (0, 0).',
  },
  {
    id: 2,
    title: '2. The Gradient Vector Arrow',
    subtitle: 'Direction of Steepest Descent $-\\nabla J$',
    objective: 'Click play to watch the gradient vector arrow point downhill.',
    concept:
      'The gradient vector ∇J(w) points in the direction of greatest increase in loss. Therefore, gradient descent moves in the opposite direction (-∇J) to decrease loss most rapidly.',
    formula: '\\nabla J(w_1, w_2) = \\begin{bmatrix} \\frac{\\partial J}{\\partial w_1} \\\\ \\frac{\\partial J}{\\partial w_2} \\end{bmatrix} = \\begin{bmatrix} w_1 \\\\ 3 w_2 \\end{bmatrix}',
    presetParams: {
      surfaceType: 'paraboloid',
      learningRate: 0.05,
      learningRateMode: 'optimal',
      w1Initial: 3.0,
      w2Initial: 3.0,
    },
    verification: (_params, _steps, currentStep) => currentStep >= 3,
    hint: 'Press Play and observe the green arrow. Notice how it shrinks as we approach the flat minimum where ∇J ≈ 0.',
  },
  {
    id: 3,
    title: '3. Very Small Learning Rate',
    subtitle: 'Under-stepping & Slow Convergence (α = 0.001)',
    objective: 'Observe how a very small learning rate takes hundreds of iterations.',
    concept:
      'When learning rate α is too small, weight updates Δw = -α ∇J are minuscule. The model takes tiny micro-steps, wasting computation and potentially getting stuck before reaching the minimum.',
    formula: 'w^{(t+1)} = w^{(t)} - 0.001 \\cdot \\nabla J(w^{(t)})',
    presetParams: {
      surfaceType: 'paraboloid',
      learningRate: 0.001,
      learningRateMode: 'very-small',
      w1Initial: 3.5,
      w2Initial: 3.5,
    },
    verification: (params, _steps, currentStep) => params.learningRate <= 0.005 && currentStep >= 5,
    hint: 'Notice how tiny each step is. Even after 10 steps, the point has barely moved from the starting position!',
  },
  {
    id: 4,
    title: '4. Optimal Learning Rate',
    subtitle: 'Smooth & Fast Convergence (α = 0.05)',
    objective: 'Achieve loss < 0.05 in under 20 iterations.',
    concept:
      'An optimal learning rate strikes a balance: large enough steps to converge quickly, but small enough to step smoothly without overshooting.',
    formula: 'w^{(t+1)} = w^{(t)} - 0.05 \\cdot \\nabla J(w^{(t)})',
    presetParams: {
      surfaceType: 'paraboloid',
      learningRate: 0.05,
      learningRateMode: 'optimal',
      w1Initial: 3.5,
      w2Initial: 3.5,
    },
    verification: (_params, steps, currentStep) => currentStep > 0 && steps[currentStep]?.loss < 0.1,
    hint: 'Watch how loss rapidly drops iteration after iteration until reaching near zero!',
  },
  {
    id: 5,
    title: '5. High Learning Rate & Oscillations',
    subtitle: 'Overshooting the Valley (α = 0.4)',
    objective: 'Observe zigzagging and overshooting across valley walls.',
    concept:
      'When α is large, the step size overshoots the minimum and bounces from one side of the steep canyon to the other, slowing overall downward progress.',
    formula: 'w^{(t+1)} = w^{(t)} - 0.4 \\cdot \\nabla J(w^{(t)})',
    presetParams: {
      surfaceType: 'paraboloid',
      learningRate: 0.4,
      learningRateMode: 'large',
      w1Initial: 3.5,
      w2Initial: 3.5,
    },
    verification: (params, _steps, currentStep) => params.learningRate >= 0.3 && currentStep >= 4,
    hint: 'Notice how the path zigzags back and forth across the w₂ axis because the gradient in w₂ is much steeper than in w₁!',
  },
  {
    id: 6,
    title: '6. Excessive Learning Rate & Divergence',
    subtitle: 'Exploding Loss (α = 1.8)',
    objective: 'Trigger divergence where loss explodes to infinity.',
    concept:
      'If α exceeds the stability limit (α > 2 / L where L is maximum curvature), each step lands farther away from the minimum than where it started, causing exponential divergence.',
    formula: 'J(w^{(t+1)}) > J(w^{(t)}) \\implies \\text{Divergence!}',
    presetParams: {
      surfaceType: 'paraboloid',
      learningRate: 1.8,
      learningRateMode: 'too-large',
      w1Initial: 1.5,
      w2Initial: 1.5,
    },
    verification: (params, steps, currentStep) => params.learningRate >= 1.2 && currentStep >= 3 && steps[currentStep]?.loss > steps[0]?.loss * 2,
    hint: 'Press Play to see the point shoot wildly off the landscape into infinite loss!',
  },
  {
    id: 7,
    title: '7. Navigating Saddle Points',
    subtitle: 'Zero-Gradient Plateaus on Non-Convex Surfaces',
    objective: 'Observe how standard GD gets trapped near a saddle point.',
    concept:
      'A saddle point is a region where gradients in some directions are near zero (∇J ≈ 0), causing standard gradient descent to stall even though it is not a true global minimum.',
    formula: 'J(w_1, w_2) = w_1^2 - w_2^2 + 0.1 w_1^4 + 0.1 w_2^4',
    presetParams: {
      surfaceType: 'saddle',
      learningRate: 0.05,
      momentum: 0,
      w1Initial: 0.05,
      w2Initial: 2.5,
    },
    verification: (params) => params.surfaceType === 'saddle',
    hint: 'Look at the middle plateau where the surface is flat. Standard gradient descent slows to a crawl here.',
  },
  {
    id: 8,
    title: '8. Accelerating with Momentum',
    subtitle: 'Heavy Ball Physics ($v_{t+1} = \\beta v_t + \\alpha \\nabla J$)',
    objective: 'Turn on Momentum (β = 0.9) to power through flat saddle points.',
    concept:
      'Momentum accumulates past gradient velocity like a heavy rolling ball. This builds speed down long slopes and helps push through flat plateaus and saddle points.',
    formula: 'v^{(t+1)} = \\beta v^{(t)} + \\alpha \\nabla J(w^{(t)}), \\quad w^{(t+1)} = w^{(t)} - v^{(t+1)}',
    presetParams: {
      surfaceType: 'saddle',
      learningRate: 0.05,
      momentum: 0.9,
      w1Initial: 0.05,
      w2Initial: 2.5,
    },
    verification: (params) => params.momentum >= 0.8,
    hint: 'Set Momentum slider to 0.9. Notice how velocity carries the point past the plateau!',
  },
  {
    id: 9,
    title: '9. Stochastic & Mini-Batch Noise',
    subtitle: 'Simulating Batch Noise in Neural Networks',
    objective: 'Add gradient noise to explore mini-batch SGD dynamics.',
    concept:
      'In deep learning, calculating exact gradients over millions of samples is slow. Mini-batch SGD computes noisy gradient estimates that help escape sub-optimal local minima.',
    formula: '\\tilde{\\nabla} J(w) = \\nabla J(w) + \\mathcal{N}(0, \\sigma^2)',
    presetParams: {
      surfaceType: 'himmelblau',
      learningRate: 0.03,
      noise: 0.35,
      batchMode: 'stochastic',
      w1Initial: 0,
      w2Initial: 0,
    },
    verification: (params) => params.noise > 0.1,
    hint: 'Set Noise to 0.35. The jittery motion allows the point to bounce out of local basins.',
  },
  {
    id: 10,
    title: '10. Master Optimization Challenge',
    subtitle: 'Conquer the Rosenbrock Banana Valley',
    objective: 'Reach loss < 0.5 on the Rosenbrock surface in under 35 steps!',
    concept:
      'The Rosenbrock valley is a famous benchmark. The minimum sits inside a long, curved, narrow valley. Finding the valley is easy, but converging to the global minimum (1, 1) requires expert parameter tuning!',
    formula: 'J(w_1, w_2) = (1 - w_1)^2 + 10 (w_2 - w_1^2)^2',
    presetParams: {
      surfaceType: 'rosenbrock',
      learningRate: 0.005,
      momentum: 0.85,
      w1Initial: -1.5,
      w2Initial: 2.0,
    },
    verification: (_params, steps, currentStep) => currentStep > 0 && steps[currentStep]?.loss < 0.5,
    hint: 'Combine a modest learning rate (e.g. 0.005) with high momentum (0.85 - 0.9) to slide down the banana curve smoothly!',
  },
];
