import { LessonStep } from '../types';

export const logisticLessons: LessonStep[] = [
  {
    id: 1,
    title: 'Introduction to Binary Classification',
    category: 'Foundations',
    description: 'Understand the goal of binary classification: assigning data points to one of two categories (Class 0 or Class 1).',
    explanation: 'In machine learning, binary classification models take features (like x1 and x2) and predict a probability between 0 and 1 representing the likelihood of belonging to Class 1.',
    actionHint: 'Observe the blue points (Class 0) and red points (Class 1) on the 3D canvas.',
    targetPreset: 'linear',
  },
  {
    id: 2,
    title: 'Linear Combinations & Weighted Sum (z)',
    category: 'Foundations',
    description: 'Learn how features x1 and x2 are combined into a single value z = w1*x1 + w2*x2 + b.',
    explanation: 'The parameters w1 and w2 represent feature weights (slopes), while b represents the bias (intercept). The weighted sum z moves points relative to the decision line.',
    actionHint: 'Look at the Math panel to see the active value of z for the current weights.',
    targetPreset: 'linear',
  },
  {
    id: 3,
    title: 'The Sigmoid Function σ(z)',
    category: 'Activation',
    description: 'Transform any real number z into a valid probability strictly between 0 and 1.',
    explanation: 'Linear regression outputs continuous values (-∞ to +∞), which cannot represent probabilities. The Sigmoid function σ(z) = 1 / (1 + e^-z) squashes z into (0, 1).',
    actionHint: 'Switch to the Sigmoid Explorer tab to drag z values and watch σ(z) change.',
  },
  {
    id: 4,
    title: 'The Decision Boundary',
    category: 'Decision Surface',
    description: 'The boundary line where z = 0 and σ(z) = 0.5 (equal probability).',
    explanation: 'Points on one side of the line have z > 0 (probability > 0.5), while points on the other side have z < 0 (probability < 0.5).',
    actionHint: 'Notice the white decision line dividing the red and blue regions.',
    targetPreset: 'linear',
  },
  {
    id: 5,
    title: 'Classification Threshold (τ)',
    category: 'Decision Surface',
    description: 'Convert continuous probabilities into discrete predictions using a cutoff threshold.',
    explanation: 'If P(y=1|x) ≥ threshold, predict Class 1 (Red); otherwise predict Class 0 (Blue). Default threshold is 0.5.',
    actionHint: 'Drag the Threshold slider in the Right Panel and observe how predictions shift.',
    targetThreshold: 0.5,
  },
  {
    id: 6,
    title: 'Probability Heatmap Surface',
    category: 'Visualization',
    description: 'Visualizing prediction confidence across the entire feature space.',
    explanation: 'The background heatmap shows model confidence: dark red indicates P ≈ 1.0, dark blue indicates P ≈ 0.0, and white marks the 50% decision boundary.',
    actionHint: 'Toggle heatmaps and notice how the gradient updates smoothly.',
  },
  {
    id: 7,
    title: 'Binary Cross-Entropy Loss (Log Loss)',
    category: 'Optimization',
    description: 'Quantifying prediction error when comparing probabilities against true binary labels.',
    explanation: 'BCE Loss penalizes confident wrong predictions heavily. If label = 1 and P = 0.01, loss approaches infinity!',
    actionHint: 'Check the BCE Loss formula in the Math panel.',
  },
  {
    id: 8,
    title: 'Gradient Descent for Classification',
    category: 'Optimization',
    description: 'Iteratively updating weights w and bias b to minimize Cross-Entropy Loss.',
    explanation: 'At each epoch, gradients (dw1, dw2, db) calculate the direction of steepest loss decrease and adjust model parameters.',
    actionHint: 'Press Play in the bottom playback bar to start training gradient descent.',
  },
  {
    id: 9,
    title: 'Impact of Learning Rate',
    category: 'Optimization',
    description: 'Choosing step size during parameter updates.',
    explanation: 'A learning rate that is too small trains slowly, while a rate that is too large oscillates or diverges.',
    actionHint: 'Compare different learning rates in the Right Panel.',
    targetLearningRate: 0.1,
  },
  {
    id: 10,
    title: 'The Confusion Matrix',
    category: 'Evaluation',
    description: 'Break down model performance into True Positives (TP), True Negatives (TN), False Positives (FP), and False Negatives (FN).',
    explanation: 'Accuracy alone can be misleading on imbalanced data. The Confusion Matrix provides a complete view of model outcomes.',
    actionHint: 'Hover over the 2x2 Confusion Matrix cells in the Bottom Panel.',
  },
  {
    id: 11,
    title: 'Accuracy vs Precision vs Recall',
    category: 'Evaluation',
    description: 'Understanding key metric trade-offs in classification tasks.',
    explanation: 'Precision measures exactness (TP / (TP+FP)). Recall measures completeness (TP / (TP+FN)). Increasing threshold increases precision but lowers recall.',
    actionHint: 'Vary the threshold slider and watch Precision and Recall trade off.',
  },
  {
    id: 12,
    title: 'F1 Score & ROC-AUC',
    category: 'Evaluation',
    description: 'Single-score metrics for overall classifier performance.',
    explanation: 'F1 Score is the harmonic mean of Precision and Recall. AUC (Area Under ROC Curve) measures model ranking ability across all possible thresholds.',
    actionHint: 'Observe ROC-AUC score updating in the Right Panel.',
  },
  {
    id: 13,
    title: 'Handling Slightly Overlapping Data',
    category: 'Datasets',
    description: 'Classifying real-world noisy data where classes overlap.',
    explanation: 'When data classes overlap, perfect 100% accuracy is impossible with a linear boundary. The model finds the optimal decision line that minimizes overall log loss.',
    actionHint: 'Select "Slightly Overlapping" dataset preset.',
    targetPreset: 'slightly_overlapping',
  },
  {
    id: 14,
    title: 'Highly Overlapping Datasets',
    category: 'Datasets',
    description: 'Understanding high variance and Bayes error boundaries.',
    explanation: 'With heavy overlap, decision boundaries balance False Positives and False Negatives based on the threshold setting.',
    actionHint: 'Select "Highly Overlapping" dataset preset.',
    targetPreset: 'highly_overlapping',
  },
  {
    id: 15,
    title: 'Non-Linear Datasets & Circular Boundaries',
    category: 'Non-Linearity',
    description: 'Why standard linear logistic regression fails on concentric circular data.',
    explanation: 'A straight line cannot separate an inner circle of Class 0 from an outer ring of Class 1.',
    actionHint: 'Select "Circular" dataset preset and observe linear boundary limitations.',
    targetPreset: 'circular',
  },
  {
    id: 16,
    title: 'Polynomial Feature Expansion',
    category: 'Non-Linearity',
    description: 'Transforming features to higher dimensions (x1², x2², x1*x2) to create curved decision boundaries.',
    explanation: 'By adding quadratic terms, a linear classifier in feature space becomes a curved circular or elliptical boundary in 2D space!',
    actionHint: 'Change Feature Type from Linear to Polynomial in the Right Panel.',
    targetFeatureType: 'polynomial',
  },
  {
    id: 17,
    title: 'The XOR Problem',
    category: 'Non-Linearity',
    description: 'The famous XOR dataset that requires non-linear features.',
    explanation: 'XOR requires cross-product terms (x1*x2) or neural net layers to achieve clean classification.',
    actionHint: 'Select "XOR" dataset preset and test polynomial expansion.',
    targetPreset: 'xor',
    targetFeatureType: 'polynomial',
  },
  {
    id: 18,
    title: 'Overfitting vs Regularization (L1 & L2)',
    category: 'Regularization',
    description: 'Preventing models from memorizing noise in complex datasets.',
    explanation: 'L2 (Ridge) and L1 (Lasso) regularization add a penalty to large weights, keeping decision boundaries smooth.',
    actionHint: 'Open Underfitting / Overfitting Explorer mode to compare models.',
  },
  {
    id: 19,
    title: 'Side-by-Side Model Comparison',
    category: 'Advanced',
    description: 'Comparing two models trained with different hyperparameters simultaneously.',
    explanation: 'Compare how Model A (low LR) vs Model B (high LR) converge over time.',
    actionHint: 'Switch to Comparison Mode to view dual split-screen models.',
  },
  {
    id: 20,
    title: 'Custom Interactive Data Creation',
    category: 'Mastery',
    description: 'Add your own data points or upload CSV files to test custom boundary limits.',
    explanation: 'Congratulations on reaching Step 20! You now have a complete visual and mathematical intuition for Logistic Regression.',
    actionHint: 'Click anywhere on the 3D Canvas or upload a CSV file to experiment.',
    targetPreset: 'custom',
  },
];
