import { LessonStep } from '../types';

export const nnLessons: LessonStep[] = [
  {
    id: 1,
    title: '1. What is an Artificial Neuron?',
    category: 'Perceptron Basics',
    description: 'An artificial neuron (Perceptron) is the fundamental building block of deep learning models. It receives input features, multiplies them by weights, adds a bias term, and passes the result through an activation function.',
    explanation: 'Think of a neuron as a mini decision maker. If weighted inputs exceed a certain threshold, the neuron fires (activates)!',
    actionHint: 'Click on any neuron sphere in the 3D network diagram to inspect its weights, bias, and activation value.',
    presetTopology: [2, 1],
  },
  {
    id: 2,
    title: '2. Inputs & Weights (z = w₁x₁ + w₂x₂)',
    category: 'Perceptron Basics',
    description: 'Inputs x₁, x₂ represent input features. Weights w₁, w₂ dictate how important each feature is in influencing the neuron output.',
    explanation: 'Positive weights strengthen positive signals (Cyan connections); negative weights invert signals (Crimson connections). Connection thickness represents weight magnitude.',
    actionHint: 'Observe the connection line colors and thickness in the 3D network.',
    presetTopology: [2, 1],
  },
  {
    id: 3,
    title: '3. The Role of Bias (b)',
    category: 'Perceptron Basics',
    description: 'Bias is an adjustable constant added to the weighted sum (z = Σ wᵢxᵢ + b). It shifts the activation function left or right.',
    explanation: 'Without bias, the decision boundary line would always be forced to pass directly through the coordinate origin (0,0).',
    actionHint: 'Notice how the bias value changes per neuron in the right panel readouts.',
    presetTopology: [2, 1],
  },
  {
    id: 4,
    title: '4. Activation Functions: Sigmoid & Tanh',
    category: 'Activation Functions',
    description: 'Activation functions introduce non-linearity, enabling neural networks to learn complex non-linear patterns beyond simple straight lines.',
    explanation: 'Sigmoid squeezes outputs into range (0, 1) producing probabilities; Tanh squeezes outputs into (-1, 1).',
    actionHint: 'Switch activation functions in the right panel and observe the decision boundary shift.',
    presetTopology: [2, 3, 1],
    presetConfig: { activation: 'sigmoid' },
  },
  {
    id: 5,
    title: '5. ReLU & Leaky ReLU',
    category: 'Activation Functions',
    description: 'ReLU (Rectified Linear Unit) outputs max(0, z). It is the default activation function in modern deep learning architectures because it avoids vanishing gradients.',
    explanation: 'Leaky ReLU retains a small 0.01 slope for negative inputs to prevent "dying neurons".',
    actionHint: 'Select ReLU in the right panel and notice how fast the network converges during training.',
    presetTopology: [2, 4, 1],
    presetConfig: { activation: 'relu' },
  },
  {
    id: 6,
    title: '6. Multi-Layer Feedforward Topology',
    category: 'Network Architecture',
    description: 'Connecting neurons in sequential layers creates a Deep Neural Network (DNN). Signal flows forward from Input Layer ➔ Hidden Layers ➔ Output Layer.',
    explanation: 'Each hidden layer extracts progressively higher-level feature representations from raw input features.',
    actionHint: 'Use the Network Builder to add hidden layers to the 3D visualizer.',
    presetTopology: [2, 4, 3, 1],
  },
  {
    id: 7,
    title: '7. Hidden Layers & Feature Representation',
    category: 'Network Architecture',
    description: 'Neurons in hidden layers act as feature detectors. Early layers learn simple linear splits; deeper layers combine splits into complex curves and enclosed decision boundaries.',
    explanation: 'For non-linear datasets like Concentric Circles or XOR, at least one hidden layer with non-linear activation is strictly required.',
    actionHint: 'Set dataset to XOR and watch hidden layer neurons learn distinct half-plane features.',
    presetTopology: [2, 4, 1],
    presetConfig: { datasetType: 'xor' },
  },
  {
    id: 8,
    title: '8. Output Layer & Binary Classification',
    category: 'Network Architecture',
    description: 'The final output neuron applies a Sigmoid activation to produce a continuous prediction probability P(y=1|X) between 0% and 100%.',
    explanation: 'If P(y=1) ≥ 0.5, the point is classified as Red (Class 1); otherwise Blue (Class 0).',
    actionHint: 'Click on the output neuron to inspect final predicted probability.',
    presetTopology: [2, 4, 1],
  },
  {
    id: 9,
    title: '9. Loss Functions: Binary Cross Entropy',
    category: 'Loss & Error',
    description: 'Loss measures prediction error across the dataset. Binary Cross Entropy (BCE) heavily penalize confident incorrect predictions.',
    explanation: 'L_BCE = -[y log(ŷ) + (1-y) log(1-ŷ)]. Lower loss means better classification accuracy.',
    actionHint: 'Press Play and watch the live Loss Curve decrease smoothly in the bottom graph.',
    presetTopology: [2, 4, 1],
  },
  {
    id: 10,
    title: '10. Forward Propagation Walkthrough',
    category: 'Training Engine',
    description: 'Forward prop computes z and activation a layer by layer: z⁽ˡ⁾ = W⁽ˡ⁾a⁽ˡ⁻¹⁾ + b⁽ˡ⁾, a⁽ˡ⁾ = f(z⁽ˡ⁾).',
    explanation: 'Cyan and red particles travel left-to-right through connection lines during forward propagation.',
    actionHint: 'Press Play to watch glowing signal pulses travel through the 3D network graph.',
    presetTopology: [2, 4, 1],
  },
  {
    id: 11,
    title: '11. Output Error & Loss Gradient',
    category: 'Training Engine',
    description: 'At the end of forward propagation, loss L is evaluated against true dataset labels. The error delta at output is δ_out = ŷ - y.',
    explanation: 'This error signal forms the starting point for calculating gradient updates across all weights.',
    actionHint: 'Observe the error delta readout in the Neuron Inspector.',
    presetTopology: [2, 4, 1],
  },
  {
    id: 12,
    title: '12. Backpropagation Intuition & Chain Rule',
    category: 'Training Engine',
    description: 'Backpropagation propagates error signals backward through the network using calculus Chain Rule: ∂L/∂W⁽ˡ⁾ = δ⁽ˡ⁾ (a⁽ˡ⁻¹⁾)ᵀ.',
    explanation: 'Gradient signals travel right-to-left, adjusting every weight to reduce total loss.',
    actionHint: 'Watch connections flash during backpropagation steps.',
    presetTopology: [2, 4, 3, 1],
  },
  {
    id: 13,
    title: '13. Gradient Vector Flow',
    category: 'Training Engine',
    description: 'Gradients ∂L/∂w specify the exact direction and magnitude of steepest loss increase. Moving in -∂L/∂w reduces loss.',
    explanation: 'Gradient norm measures total optimization step magnitude across all parameters.',
    actionHint: 'Check the live Gradient Magnitude curve in the bottom analytics panel.',
    presetTopology: [2, 4, 1],
  },
  {
    id: 14,
    title: '14. Weight Updates (w_new = w - α · ∂L/∂w)',
    category: 'Training Engine',
    description: 'After backpropagation computes partial derivatives, weights update downhill by step size scaled by learning rate α.',
    explanation: 'As weights update, connection line thickness and colors dynamically shift in the 3D canvas.',
    actionHint: 'Adjust learning rate slider in right panel to see update speed change.',
    presetTopology: [2, 4, 1],
  },
  {
    id: 15,
    title: '15. Learning Rate Hyperparameter Tuning',
    category: 'Hyperparameter Optimization',
    description: 'Learning rate α determines step size. Too small (α=0.001) causes slow training; too large (α=1.0) causes overshooting.',
    explanation: 'Finding an optimal learning rate (e.g. α=0.03) enables fast, stable convergence.',
    actionHint: 'Test different learning rates in Model Comparison mode.',
    presetTopology: [2, 4, 1],
  },
  {
    id: 16,
    title: '16. Momentum Optimization',
    category: 'Hyperparameter Optimization',
    description: 'Momentum accumulates velocity v = βv + α∇W to accelerate descent through flat plateaus and overcome noisy gradients.',
    explanation: 'Functions like a heavy ball rolling down a hilly terrain.',
    actionHint: 'Select Momentum optimizer in the right panel and compare convergence speed.',
    presetTopology: [2, 4, 1],
    presetConfig: { optimizer: 'momentum' },
  },
  {
    id: 17,
    title: '17. RMSProp & Adaptive Rates',
    category: 'Hyperparameter Optimization',
    description: 'RMSProp scales learning rates inversely by root-mean-square of recent gradients, dampening oscillations in steep directions.',
    explanation: 'Particularly effective for non-stationary, noisy datasets.',
    actionHint: 'Select RMSProp optimizer in right panel.',
    presetTopology: [2, 4, 1],
    presetConfig: { optimizer: 'rmsprop' },
  },
  {
    id: 18,
    title: '18. Adam Optimizer (Adaptive Moment Estimation)',
    category: 'Hyperparameter Optimization',
    description: 'Adam combines Momentum (first moment m) and RMSProp (second moment v). It is the premier state-of-the-art optimizer in modern Deep Learning.',
    explanation: 'Provides fast, robust convergence across almost all network architectures.',
    actionHint: 'Observe Adam optimizer performance on complex datasets like Spiral.',
    presetTopology: [2, 6, 4, 1],
    presetConfig: { optimizer: 'adam' },
  },
  {
    id: 19,
    title: '19. Vanishing Gradient Problem',
    category: 'Deep Learning Challenges',
    description: 'In deep networks with Sigmoid activations, derivatives σ\'(z) ≤ 0.25 cause gradient signals to exponentially collapse toward zero in early layers.',
    explanation: 'When gradients vanish, early layers stop learning completely!',
    actionHint: 'Switch to Gradient Flow Inspector view mode to detect vanishing gradients.',
    presetTopology: [2, 5, 5, 5, 1],
    presetConfig: { activation: 'sigmoid' },
  },
  {
    id: 20,
    title: '20. Exploding Gradient Problem',
    category: 'Deep Learning Challenges',
    description: 'Large weights cause gradients to multiply exponentially layer by layer, causing parameters to explode to NaN / Infinity.',
    explanation: 'Controlled via gradient clipping, weight initialization, and batch normalization.',
    actionHint: 'Observe gradient magnitude warnings in right panel readouts.',
    presetTopology: [2, 5, 5, 1],
  },
  {
    id: 21,
    title: '21. The Non-Linear XOR Problem',
    category: 'Classic ML Problems',
    description: 'A single perceptron cannot solve XOR because Class 0 and Class 1 points are not linearly separable by a straight line.',
    explanation: 'Adding 1 hidden layer with 4 neurons creates 4 half-planes that combine into non-linear decision regions.',
    actionHint: 'Select XOR dataset and train a 2-4-1 network to observe non-linear classification.',
    presetTopology: [2, 4, 1],
    presetConfig: { datasetType: 'xor' },
  },
  {
    id: 22,
    title: '22. Concentric Circles Dataset',
    category: 'Classic ML Problems',
    description: 'Concentric Circles require enclosed circular decision boundaries.',
    explanation: 'Hidden neurons create intersecting linear bounds that enclose the inner class circle.',
    actionHint: 'Select Circle dataset and watch boundary heatmap form a circular region.',
    presetTopology: [2, 5, 1],
    presetConfig: { datasetType: 'circle' },
  },
  {
    id: 23,
    title: '23. Archimedean Spiral Dataset',
    category: 'Classic ML Problems',
    description: 'The Spiral dataset is one of the hardest 2D benchmarks, requiring deep multi-layer representation learning.',
    explanation: 'Requires a deeper architecture (e.g. 2-8-6-1) and non-linear activations like Tanh or ReLU.',
    actionHint: 'Select Spiral dataset and build a 4-layer network to classify both spirals.',
    presetTopology: [2, 8, 6, 1],
    presetConfig: { datasetType: 'spiral', activation: 'tanh' },
  },
  {
    id: 24,
    title: '24. Overfitting & L1/L2 Regularization',
    category: 'Regularization & Generalization',
    description: 'Overly complex networks memorize noise rather than learning true patterns. L1 (Lasso) and L2 (Ridge) penalize large weights.',
    explanation: 'L2 regularization adds ½λ Σ w² to loss, encouraging smooth decision boundaries.',
    actionHint: 'Increase L2 Lambda slider in right panel to simplify complex boundaries.',
    presetTopology: [2, 8, 8, 1],
    presetConfig: { l2Lambda: 0.05 },
  },
  {
    id: 25,
    title: '25. Master Neural Network Challenge',
    category: 'Capstone Challenge',
    description: 'Congratulations! You have mastered Neural Network architecture, Forward/Backprop mechanics, activations, optimizers, and decision boundaries.',
    explanation: 'Now use the Free Playground Mode to design custom topologies and train models on any dataset!',
    actionHint: 'Experiment with custom topologies, datasets, and hyperparameters in Free Playground mode.',
    presetTopology: [2, 6, 4, 1],
  },
];
